### PR TITLE
fix: missing block while waiting for operator state history

### LINKED ISSUE #265: Remove the use of current block number in start_service in Operators info service
Currently we use start the service with the current block [number](https://github.com/Layr-Labs/eigensdk-rs/blob/36ac6cd05d6cc26f0d9d24e66bb3978758bed8f2/crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs#L232) .

Correct way should be to return the last block [query_past_registered_operator_events_and_fill_db](https://github.com/Layr-Labs/eigensdk-rs/blob/36ac6cd05d6cc26f0d9d24e66bb3978758bed8f2/crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs#L228) queried and start the service from  (last_block_queried + 1 ) blocks to not miss blocks.

h/t @RonTuretzky

### PR DESCRIPTION
**Pull request by najeal**
Fixes #265 

### What Changed?
when starting service operatorsinfo_inmemory, the service starts to listen for new events while fetching operator state history. This avoid waiting to get the history then miss blocks.

### Reviewer Checklist

- [ ] New features are tested and documented
- [ ] PR updates the changelog with a description of changes
- [ ] PR has one of the `changelog-X` labels (if applies)
- [ ] Code deprecates any old functionality before removing it

### CODE REVIEW

File: crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs [hunk 1]
```diff
@@ -260,8 +327,17 @@ impl OperatorInfoServiceInMemory {
             tokio::select! {
                 _ = cancellation_token.cancelled() => {
                     self.logger.info("Cancellation signal received, stopping the stream.", "eigen-services-operatorsinfo.start_service");
+                    handle.abort();
                     break;
                 },
+                res = rx.recv() => {
+                    match res {
+                        Some(Err(err)) => {
```
Comment (najeal) [inline crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs:335]: this is used to stop service as it is done previously when history fetching fails.

File: crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs [hunk 2]
```diff
@@ -43,12 +43,19 @@ pub struct OperatorInfoServiceInMemory {
...
+
 /// State of the operator info service.
 #[derive(Debug, Clone)]
 struct OperatorState {
-    operator_info_data: Arc<RwLock<HashMap<Address, OperatorPubKeys>>>,
-    operator_addr_to_id: Arc<RwLock<HashMap<Address, OperatorId>>>,
-    socket_dict: Arc<RwLock<HashMap<OperatorId, String>>>,
+    operator_info_data: Arc<RwLock<HashMap<Address, (StateSource, OperatorPubKeys)>>>,
+    operator_addr_to_id: Arc<RwLock<HashMap<Address, (StateSource, OperatorId)>>>,
+    socket_dict: Arc<RwLock<HashMap<OperatorId, (StateSource, String)>>>,
```
Comment (najeal) [inline crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs:58]: StateSource is used to now if the data we try to insert is more recent or not than the one already store.
Trying to replace a Event data by a History data should be avoided.

File: crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs (hunk 1 above)
Comment (supernovahs) [reply crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs:338]: i tthink we can add a log here, stating that history fetching failed

File: crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs [hunk 3]
```diff
@@ -146,20 +154,55 @@ impl OperatorInfoServiceInMemory {
...
+                                keys,
+                                socket_info,
+                                state_src,
+                            ) => {
                                 if let (Some(addr), Some(keys)) = (addr, keys) {
                                     let mut data = operator_state.operator_info_data.write().await;
-                                    data.insert(addr, *keys.clone());
+                                    match data.get(&addr) {
+                                        Some((entry_src, _))
+                                            if *entry_src == StateSource::Event
```
Comment (supernovahs) [inline crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs:168]: can you add comment here that we don't overwrite latest data with historic one

Comment (supernovahs) [reply crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs:168]: same at other places

**Review by supernovahs — CHANGES_REQUESTED** [review]

**Comment by supernovahs** [comment]
CHANGELOG add pending

File: crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs (hunk 1 above)
Comment (najeal) [reply crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs:338]: done

File: crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs (hunk 3 above)
Comment (najeal) [reply crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs:168]: done

**Review by supernovahs — APPROVED** [review]
LGTM. pending CHANGELOG.md addition under the head Other Changes  @najeal

**Comment by najeal** [comment]
@supernovahs sorry for the misunderstanding, it should be good now ! 👍

**Review by supernovahs — APPROVED** [review]

**Review by MegaRedHand — APPROVED** [review]
