### PR TITLE
fix: `avsregistry/reader` tests

### LINKED ISSUE #307: refactor: improve tests cases in `avsregistry/reader`
We were previously testing the `avsregistry/reader` against Holesky. In a recent [PR](https://github.com/Layr-Labs/eigensdk-rs/pull/306), the method that create `avs_reader` was modified to use Anvil. This change caused issues in tests related to methods with `block_number`.

I have added an assert error as a temporary fix for
- `test_get_operators_stake_in_quorums_at_block`
- `test_get_operators_stake_in_quorums_at_block_operator_id`
- `test_get_operators_stake_in_quorums_at_current_block`
- `test_get_operators_stake_in_quorums_of_operator_at_current_block`
- `test_get_operators_stake_in_quorums_of_operator_at_block`

Example:
```rust
#[tokio::test]
    async fn test_get_operators_stake_in_quorums_at_block_operator_id() {
        let (_container, http_endpoint, _ws_endpoint) = start_anvil_container().await;
        let avs_reader = build_avs_registry_chain_reader(http_endpoint.clone()).await;

        let operator_id = U256::from_str(
            "35344093966194310405039483339636912150346494903629410125452342281826147822033",
        )
        .unwrap();

        // revert: RegistryCoordinator.getQuorumBitmapIndexAtBlockNumber: no bitmap update found for operatorId
        let operators_stake = avs_reader
            .get_operators_stake_in_quorums_at_block_operator_id(1245842, operator_id.into())
            .await;

        assert!(operators_stake.is_err());
    }
```

The goal is to create a more comprehensive test that ensures the function does not return an error and verifies that the returned value is correct.

### PR DESCRIPTION
**Pull request by damiramirez**
### What Changed?

A temporary fix was introduced in [this PR](https://github.com/Layr-Labs/eigensdk-rs/pull/306) for some test cases. This PR aims to provide a proper fix by adding the correct setup for the tests.

Close #307 

### Reviewer Checklist

- [ ] New features are tested and documented
- [ ] PR updates the changelog with a description of changes
- [ ] PR has one of the `changelog-X` labels (if applies)
- [ ] Code deprecates any old functionality before removing it

### CODE REVIEW

File: crates/chainio/clients/avsregistry/src/reader.rs [hunk 1]
```diff
@@ -665,69 +667,171 @@ mod tests {
...
+            .await
+            .unwrap();
     }
 
     #[tokio::test]
     async fn test_get_operators_stake_in_quorums_of_operator_at_current_block() {
-        let (_container, http_endpoint, _ws_endpoint) = start_anvil_container().await;
+        let (_container, http_endpoint, _ws_endpoint) = start_m2_anvil_container().await;
+
+        let private_key =
```
Comment (pablodeymo) [inline crates/chainio/clients/avsregistry/src/reader.rs]: it's better to abstract the keys

Comment (damiramirez) [reply crates/chainio/clients/avsregistry/src/reader.rs]: Done [a942d62](https://github.com/Layr-Labs/eigensdk-rs/pull/338/commits/a942d620cbe0b56f45d88cc9e1fde0a7ec41eaeb)

**Review by pablodeymo — DISMISSED** [review]

**Review by MegaRedHand — DISMISSED** [review]

**Review by pablodeymo — APPROVED** [review]
